apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ghactions
spec:
  replicas: 4
  selector:
    matchLabels:
      app: test-ghactions
  template:
    metadata:
      labels:
        app: test-ghactions
    spec:
      containers:
      - name: resume
        image: eddisonso/test-ghactions:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500M"
            cpu: "500m"
        ports:
        - containerPort: 8000 
---
apiVersion: v1
kind: Service
metadata:
  name: test-ghactions-lb
spec:
  selector:
    app: test-ghactions
  ports:
  - port: 8000
    nodePort: 30000
  type: LoadBalancer
