version: "3"
services:
  ismart_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "test-ghactions"
    container_name: "test-ghactionsi"
    ports:
      - "8000:8000"
    restart: unless-stopped
