name: build-and-deploy

on:
  push:
    branches:
      - "main"

env:
  GKE_CLUSTER: main-cluster     # Add your cluster name here.
  GKE_ZONE: us-east1            # Add your cluster zone here.
  TIMESTAMP: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      TIMESTAMP: ${{ steps.set-time.outputs.TIMESTAMP }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "TIMESTAMP=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

      - id: set-time
        name: Set Output Timestamp
        run: echo "TIMESTAMP=${{ env.TIMESTAMP }}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: eddisonso/test-ghactions:${{ env.TIMESTAMP }}

      - name: Pass Timestamp to Deploy Stage
        id: pass-ts
        run: |
          echo "::set-output name=TIMESTAMP::$TIMESTAMP"
  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - id: "auth"
        name: "authenticate with google cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: "hubba-411805"

      - name: Upload yaml
        uses: actions/upload-artifact@v4
        with:
          name: yaml file
          path: build.yaml

      - name: Deploy
        run: |-
          kubectl set image deployment/test-ghactions test-ghactions=eddisonso/test-ghactions:${{needs.build-and-push.outputs.TIMESTAMP}}
